name: "Composite Action Test Errors"
description: "Run a simple composite action"
env:
  NAME2: test2
  SERVER: development
inputs:
  your_name:
    description: 'lol'
    default: 'Ethan'
runs:
    using: "composite"
    steps:
      - run: echo hello world 1
        id: test1
      - run: echo hello world 2
        id: test1
